#!/bin/bash

# Load environment variables
export NEXT_PUBLIC_SUPABASE_URL="https://aeojiqvwwmpfpxsttzca.supabase.co"
export NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlb2ppcXZ3d21wZnB4c3R0emNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDEyOTYsImV4cCI6MjA2MDA3NzI5Nn0.PSoTvb_IZ9UFu9b3qr2o7nY3NwjBFhAc7h5d6C1MPtE"
export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlb2ppcXZ3d21wZnB4c3R0emNhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDUwMTI5NiwiZXhwIjoyMDYwMDc3Mjk2fQ.xTKqiXxUj6ISgpwLHqbPT0Y4A-J8iqr1zO9YG1MmbC0"

# Run the schema application
./scripts/apply-schema.sh
